Y = 700
MENU_WIDTH = 140
X = Y + MENU_WIDTH


SPEED_HACK = 0.2
FOOD_PER_PX = 0.2 * SPEED_HACK
# MAX_AGE = 3000;
# AGING = 1 * SPEED_HACK;
FITNESS_DEGRADATION = 0.02 * SPEED_HACK
FOOD_PER_RAD = 2 * SPEED_HACK
MIN_CREATURES_COUNT = 50
FOOD_COUNT = 50
CREATURE_SIZE = 7  # px
CREATURE_SPEED = 5 * CREATURE_SIZE * SPEED_HACK  # own sizes / iteration
CREATURE_TURNING_SPEED = 0.7 * SPEED_HACK  # rads / iteration
ACCELERATION = 0.6 * CREATURE_SIZE * SPEED_HACK
BRAIN_INIT_RANGE = 1.3
FOOD_COST = 15
STARTING_FITNESS = 50
# STARTING_FITNESS_RANGE = 5;
BIRTH_FITNESS_COST = 60
MUTAGEN_MULTIPLIER = 0.02
FIELD_X_OFFSET = MENU_WIDTH
FIELD_SIZE_X = FIELD_SIZE_Y = Y
BIRTH_NEURON_ACTIVATION = 0.
SURFACE_ROUGHNESS = 0.2

GRID_SEGMENTS = 14
CELL_SIZE = FIELD_SIZE_X / GRID_SEGMENTS

defaultHiddenLayersNeuronCount = [6, 6]
